"""snapz: lightweight directory snapshot CLI.

Public API entry points live in :mod:`snapz.api`.
"""

__version__ = "2.2.0"

from snapz.api import (
    add_local_excludes,
    adopt_archive,
    check,
    delete,
    diff,
    execute_prune,
    export,
    export_bundle,
    find,
    find_relocation_candidates,
    gc,
    import_bundle,
    init_source,
    list_all,
    list_archives,
    list_snapshots,
    migrate,
    plan_prune,
    protect,
    rename,
    auto_relocate_path,
    auto_relocate_sources,
    relocate_source,
    revert,
    restore,
    restore_archive,
    restore_estimate,
    save,
    show,
    stats,
    tag_add,
    tag_remove,
    list_tags,
    undo,
    unprotect,
)

__all__ = [
    "__version__",
    "save",
    "adopt_archive",
    "check",
    "list_snapshots",
    "list_all",
    "list_archives",
    "delete",
    "rename",
    "relocate_source",
    "protect",
    "unprotect",
    "show",
    "restore",
    "restore_archive",
    "restore_estimate",
    "export",
    "export_bundle",
    "import_bundle",
    "init_source",
    "gc",
    "find_relocation_candidates",
    "auto_relocate_path",
    "auto_relocate_sources",
    "diff",
    "add_local_excludes",
    "stats",
    "plan_prune",
    "execute_prune",
    "revert",
    "find",
    "undo",
    "migrate",
    "tag_add",
    "tag_remove",
    "list_tags",
]
