"""Programmatic entry points.

These are the functions external integrations (e.g. ``topics-bot``'s
``SnapshotBot``) should import. They never prompt the user — interactive
behaviour lives in :mod:`snapz.cli`.

The implementation is split by feature in ``snapz._api_*`` modules; this
module remains the stable compatibility facade.
"""

from __future__ import annotations

from snapz import archive, cas, events, filecache, preferences
from snapz.archive import ArchiveMember, PackResult, ProgressCallback, WalkResult
from snapz.config import META_SUFFIX, RuntimeConfig, default_config
from snapz.store import (
    ARCHIVE_SUFFIXES,
    DirEntry,
    DirMeta,
    SnapshotMeta,
    Store,
    read_source_marker,
    source_identity,
    source_marker_path,
    write_source_marker,
)
from snapz._api_bundle import (
    BUNDLE_FORMAT_VERSION,
    BUNDLE_META_NAME,
    BundleExportOutcome,
    BundleImportOutcome,
    _open_bundle_tar_reader,
    _open_bundle_tar_writer,
    export_bundle,
    import_bundle,
)
from snapz._api_core import (
    AutoRelocateOutcome,
    DiffResult,
    ExportOutcome,
    FileChange,
    RelocationCandidate,
    RelocationSkip,
    RestoreEstimate,
    RestoreOutcome,
    SaveOutcome,
    SourceInitOutcome,
    _delete_snapshot_with_refs,
    _extract_cas,
    _load_manifest_or_raise,
    _record_event,
    _resolve_archive,
    _source_path,
    add_local_excludes,
    adopt_archive,
    auto_relocate_path,
    auto_relocate_sources,
    delete,
    diff,
    estimate,
    export,
    find_relocation_candidates,
    init_source,
    list_all,
    list_archives,
    list_snapshots,
    list_tags,
    protect,
    read_live_bytes,
    read_snapshot_bytes,
    relocate_source,
    rename,
    restore,
    restore_archive,
    restore_estimate,
    save,
    show,
    tag_add,
    tag_remove,
    unprotect,
)
from snapz._api_find import FindHit, FindResult, _match_path, find
from snapz._api_maintenance import (
    CheckIssue,
    CheckResult,
    GcResult,
    MigrateOutcome,
    check,
    gc,
    migrate,
)
from snapz._api_prune import (
    PruneOutcome,
    PrunePlan,
    _auto_prune_after_save,
    execute_prune,
    plan_prune,
)
from snapz._api_revert import RevertOutcome, revert
from snapz._api_stats import StatsEntry, _STATS_CACHE_MISS, stats
from snapz._api_undo import UndoOutcome, find_undo_target, undo

__all__ = [
    "ARCHIVE_SUFFIXES",
    "ArchiveMember",
    "AutoRelocateOutcome",
    "BUNDLE_FORMAT_VERSION",
    "BUNDLE_META_NAME",
    "BundleExportOutcome",
    "BundleImportOutcome",
    "CheckIssue",
    "CheckResult",
    "DiffResult",
    "DirEntry",
    "DirMeta",
    "ExportOutcome",
    "FileChange",
    "FindHit",
    "FindResult",
    "GcResult",
    "META_SUFFIX",
    "MigrateOutcome",
    "PackResult",
    "ProgressCallback",
    "PruneOutcome",
    "PrunePlan",
    "RelocationCandidate",
    "RelocationSkip",
    "RestoreEstimate",
    "RestoreOutcome",
    "RevertOutcome",
    "RuntimeConfig",
    "SaveOutcome",
    "SnapshotMeta",
    "SourceInitOutcome",
    "StatsEntry",
    "Store",
    "UndoOutcome",
    "WalkResult",
    "add_local_excludes",
    "adopt_archive",
    "archive",
    "auto_relocate_path",
    "auto_relocate_sources",
    "cas",
    "check",
    "default_config",
    "delete",
    "diff",
    "estimate",
    "events",
    "execute_prune",
    "export",
    "export_bundle",
    "filecache",
    "find",
    "find_relocation_candidates",
    "find_undo_target",
    "gc",
    "import_bundle",
    "init_source",
    "list_all",
    "list_archives",
    "list_snapshots",
    "list_tags",
    "migrate",
    "plan_prune",
    "preferences",
    "protect",
    "read_live_bytes",
    "read_snapshot_bytes",
    "read_source_marker",
    "relocate_source",
    "rename",
    "restore",
    "restore_archive",
    "restore_estimate",
    "revert",
    "save",
    "show",
    "source_identity",
    "source_marker_path",
    "stats",
    "tag_add",
    "tag_remove",
    "undo",
    "unprotect",
    "write_source_marker",
    "_auto_prune_after_save",
    "_delete_snapshot_with_refs",
    "_extract_cas",
    "_load_manifest_or_raise",
    "_match_path",
    "_open_bundle_tar_reader",
    "_open_bundle_tar_writer",
    "_record_event",
    "_resolve_archive",
    "_source_path",
]
