"""ncdu-style curses TUI for snapz.

The implementation is split by view in ``snapz._tui_*`` modules; this
module remains the stable compatibility facade for CLI code and tests.
"""

from __future__ import annotations

from snapz._tui_browser import (
    BrowseAction,
    BrowseRow,
    _RevertBrowserRow,
    _browse_descendant_paths,
    _browse_parent,
    _compute_manifest_differs,
    _revert_browser_rows,
    _revert_descendant_paths,
    _revert_parent,
    _revert_selection_marker,
    _revert_toggle_path,
    browse_manifest,
    browse_rows,
    browse_selection_marker,
    browse_toggle_path,
    run_revert_picker,
)
from snapz._tui_common import (
    LIVE,
    DeferredRestore,
    _Action,
    _Column,
    _Row,
    _addstr,
    _build_alist_rows,
    _build_list_rows,
    _compute_columns,
    _confirm_popup,
    _details_popup,
    _draw,
    _draw_key_hints,
    _filter_predicate,
    _format_row,
    _init_colors,
    _prompt_input,
    _read_filter_pattern,
    _render_row,
    _run_loop,
    _truncate,
)
from snapz._tui_diff import (
    _decode_for_diff,
    _format_diff_change,
    _parent_dir_pattern,
    _run_file_preview,
    _run_unified_diff_for_change,
    run_diff_view,
)
from snapz._tui_list import run_alist_view, run_list_view
from snapz._tui_picker import prompt_text, run_archive_picker, run_snapshot_picker

__all__ = [
    "LIVE",
    "BrowseAction",
    "BrowseRow",
    "DeferredRestore",
    "_Action",
    "_Column",
    "_RevertBrowserRow",
    "_Row",
    "_addstr",
    "_browse_descendant_paths",
    "_browse_parent",
    "_build_alist_rows",
    "_build_list_rows",
    "_compute_columns",
    "_compute_manifest_differs",
    "_confirm_popup",
    "_decode_for_diff",
    "_details_popup",
    "_draw",
    "_draw_key_hints",
    "_filter_predicate",
    "_format_diff_change",
    "_format_row",
    "_init_colors",
    "_parent_dir_pattern",
    "_prompt_input",
    "_read_filter_pattern",
    "_render_row",
    "_revert_browser_rows",
    "_revert_descendant_paths",
    "_revert_parent",
    "_revert_selection_marker",
    "_revert_toggle_path",
    "_run_file_preview",
    "_run_loop",
    "_run_unified_diff_for_change",
    "_truncate",
    "browse_manifest",
    "browse_rows",
    "browse_selection_marker",
    "browse_toggle_path",
    "prompt_text",
    "run_alist_view",
    "run_archive_picker",
    "run_diff_view",
    "run_list_view",
    "run_revert_picker",
    "run_snapshot_picker",
]
